### ISSUE TITLE
OSError: libespeak-ng.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by h0rv** [Reqeique/Dimits#2]
Hi! I came across this package for easier way to inferface with Piper - great work!

I am running into an error on installation however.

Error:

```
['voice-ca-upc_ona-x-low', 'voice-ca-upc_pau-x-low', 'voice-da-nst_talesyntese-medium', 'voice-de-eva_k-x-low', 'voice-de-karlsson-low', 'voice-de-kerstin-low', 'voice-de-pavoque-low', 'voice-de-ramona-low', 'voice-de-thorsten-low', 'voice-el-gr-rapunzelina-low', 'voice-en-gb-alan-low', 'voice-en-gb-southern_english_female-low', 'voice-en-us-amy-low', 'voice-en-us-danny-low', 'voice-en-us-kathleen-low', 'voice-en-us-lessac-low', 'voice-en-us-lessac-medium', 'voice-en-us-libritts-high', 'voice-en-us-ryan-high', 'voice-en-us-ryan-low', 'voice-en-us-ryan-medium', 'voice-en-us_lessac', 'voice-es-carlfm-x-low', 'voice-es-mls_10246-low', 'voice-es-mls_9972-low', 'voice-fi-harri-low', 'voice-fr-gilles-low', 'voice-fr-mls_1840-low', 'voice-fr-siwis-low', 'voice-fr-siwis-medium', 'voice-is-bui-medium', 'voice-is-salka-medium', 'voice-is-steinn-medium', 'voice-is-ugla-medium', 'voice-it-riccardo_fasol-x-low', 'voice-kk-iseke-x-low', 'voice-kk-issai-high', 'voice-kk-raya-x-low', 'voice-ne-google-medium', 'voice-ne-google-x-low', 'voice-nl-mls_5809-low', 'voice-nl-mls_7432-low', 'voice-nl-nathalie-x-low', 'voice-nl-rdh-medium', 'voice-nl-rdh-x-low', 'voice-no-talesyntese-medium', 'voice-pl-mls_6892-low', 'voice-pt-br-edresson-low', 'voice-ru-irinia-medium', 'voice-sv-se-nst-medium', 'voice-uk-lada-x-low', 'voice-vi-25hours-single-low', 'voice-vi-vivos-x-low', 'voice-zh-cn-huayan-x-low', 'voice-zh_CN-huayan-medium']
[2024-03-27 20:43:09] Using /home/horv/piper/en-us-danny-low.onnx
/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Traceback (most recent call last):
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/espeak_phonemizer/__init__.py", line 224, in _maybe_init
    self.lib_espeak = ctypes.cdll.LoadLibrary("libespeak-ng.so")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libespeak-ng.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/horv/Projects/diablogical/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 409, in main
    run(
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/horv/Projects/diablogical/src/server.py", line 4, in <module>
    from .tts import url_to_text, text_to_audio
  File "/home/horv/Projects/diablogical/src/tts.py", line 4, in <module>
    from dimits import Dimits
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/dimits/__init__.py", line 9, in <module>
    from .main import Dimits
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/dimits/main.py", line 219, in <module>
    Dimits("voice-en-us-danny-low").text_2_speech(text="""
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/dimits/main.py", line 195, in text_2_speech
    filepath = self.text_2_audio_file(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/dimits/main.py", line 138, in text_2_audio_file
    out_bin = ttsm(self.voice_onnx).synthesize(text,length_scale=1.0, noise_scale=1.0, noise_w=1.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/dimits/ttsmodel.py", line 105, in synthesize
    phonemes = self._text_to_phonemes(text)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/dimits/ttsmodel.py", line 126, in _text_to_phonemes
    phonemes = [_BOS] + list(self.phonemizer.phonemize(text,keep_clause_breakers=True ))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/espeak_phonemizer/__init__.py", line 91, in phonemize
    self._maybe_init()
  File "/home/horv/Projects/diablogical/.venv/lib/python3.11/site-packages/espeak_phonemizer/__init__.py", line 227, in _maybe_init
    self.lib_espeak = ctypes.cdll.LoadLibrary("libespeak-ng.so.1")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libespeak-ng.so.1: cannot open shared object file: No such file or directory
```

System info: 

```
Arch Linux x86_64
```

**Comment by Reqeique** [comment]
Have you installed these libraries in your machine ?
`sudo apt install espeak`

`sudo apt install libespeak-dev`
